// Type declarations for the WASM pitch detector module
// The actual module is generated by wasm-pack at src/wasm/pkg/

declare module "@/wasm/pkg/pitch_detector" {
  /**
   * Calculate RMS (Root Mean Square) of the signal
   */
  export function calculate_rms(samples: Float32Array): number;

  /**
   * YIN pitch detection algorithm
   * Returns the detected frequency in Hz, or -1.0 if no pitch detected
   */
  export function detect_pitch(
    samples: Float32Array,
    sample_rate: number,
  ): number;

  /**
   * YIN pitch detection with custom threshold
   */
  export function detect_pitch_with_threshold(
    samples: Float32Array,
    sample_rate: number,
    threshold: number,
  ): number;

  /**
   * Calculate the clarity/confidence of the pitch detection
   * Returns a value between 0.0 (low confidence) and 1.0 (high confidence)
   */
  export function get_pitch_clarity(
    samples: Float32Array,
    sample_rate: number,
  ): number;

  export function init_panic_hook(): void;

  export type InitInput =
    | RequestInfo
    | URL
    | Response
    | BufferSource
    | WebAssembly.Module;

  export type InitOutput = {
    readonly memory: WebAssembly.Memory;
    readonly detect_pitch: (a: number, b: number, c: number) => number;
    readonly detect_pitch_with_threshold: (
      a: number,
      b: number,
      c: number,
      d: number,
    ) => number;
    readonly calculate_rms: (a: number, b: number) => number;
    readonly get_pitch_clarity: (a: number, b: number, c: number) => number;
    readonly init_panic_hook: () => void;
    readonly __wbindgen_free: (a: number, b: number, c: number) => void;
    readonly __wbindgen_malloc: (a: number, b: number) => number;
    readonly __wbindgen_realloc: (
      a: number,
      b: number,
      c: number,
      d: number,
    ) => number;
    readonly __wbindgen_externrefs: WebAssembly.Table;
    readonly __wbindgen_start: () => void;
  };

  export type SyncInitInput = BufferSource | WebAssembly.Module;

  export function initSync(
    module: { module: SyncInitInput } | SyncInitInput,
  ): InitOutput;

  export default function __wbg_init(
    module_or_path?:
      | { module_or_path: InitInput | Promise<InitInput> }
      | InitInput
      | Promise<InitInput>,
  ): Promise<InitOutput>;
}
